channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - cmake
    - pip
    - pip:
        - tensorflow==2.4.0
        - streamlit== 1.11.1
        - opencv-python-headless
        - pillow
        - pytube
        - matplotlib
        - cuda-python
        - cudnn--python-wrappers
