channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - cmake
    - imageio
    - imageio-ffmpeg
    - ffmpeg-python
    - pip
    - pip:
        - tensorflow==2.4.0
        - streamlit
        - opencv-python-headless
        - pillow
        - cuda-python
        - cudnn-python-wrappers
        - face-recognition
        - face_recognition
        - Js2Py
        - pytube
        - matplotlib
