channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - cmake
    - pip
    - pip:
        - tensorflow==2.4.0
        - streamlit
        - opencv-python-headless
        - pillow
        - pytube
        - matplotlib
        - ffmpeg-python
        - facial_recognition
        - imageio
        - imageio-ffmpeg
        - facial-recognition
