channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - cmake
    - pip
    - pip:
        - tensorflow-cpu
        - streamlit
        - opencv-python-headless
        - pillow
        - pytube
        - matplotlib
        - face_recognition
        - face-recognition 
        - imageio-ffmpeg
        - imageio
        - ffmpeg-python
