channels:
     - conda-forge
dependencies:
     - dlib
     - pip
     - numpy
     - opencv
     - pip:
       - matplotlib
       - tensorflow==2.4.0
       - streamlit
       - cmake
       - opencv-python-headless
       - face-recognition
       - imageio-ffmpeg
       - imageio
       - pillow
       - ffmpeg-python
       - cuda-python
       - cudnn-python-wrappers
       - face_recognition
