channels:
  - anaconda 
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - cmake
    - pip
    - pip:
        - tensorflow==2.4.0
        - streamlit
        - opencv-python-headless
        - pillow
        - cuda-python
        - cudnn-python-wrappers
        - face-recognition
        - imageio-ffmpeg
        - imageio
        - ffmpeg-python
        - pytube
