channels:
  - anaconda 
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - pip
    - cmake
    - pip:
        - tensorflow==2.4.0
        - streamlit
        - matplotlib
        - opencv-python-headless
        - pillow
        - cuda-python
        - cudnn-python-wrapper
