channels:
  - conda-forge
  - defaults 
dependencies:
    - python=3.7
    - conda
    - pystan=2.19.1.1
    - fbprophet=0.7.1
    - pandas=1.3.4
    - pillow=9.0.1
    - scipy=1.7.3
    - statsmodels=0.13.2
    - keras==2.8.0
    - numpy
    - cmake
    - pip=21.2.4
    - pip:
        - tensorflow==2.8.0
        - streamlit
        - opencv-python-headless
        - pillow
        - pytube
        - matplotlib
        - cuda-python
        - cudnn--python-wrappers
