channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - cmake
    - opencv
    - pip
    - pip:
        - tensorflow==2.4.0
        - streamlit
        - pillow
        - cuda-python
        - cudnn-python-wrappers
        - face_recognition
        - imageio
        - imageio-ffmpeg
        - ffmpeg-python
        - Js2Py
        - pytube
        - matplotlib
