channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - pip
    - pip:
        - tensorflow==2.4.0
        - streamlit
        - opencv-python-headless
        - pillow
        - pytube
        - matplotlib
