channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - dlib
    - numpy
    - scipy
    - cmake
    - conda
    - pip==21.2.4:
        - tensorflow==2.5.0
        - streamlit
        - opencv-python-headless
        - pillow
        - pytube
        - matplotlib
        - cuda-python
        - cudnn--python-wrappers
