name:test-env
channels:
     - conda-forge
dependencies:
- dlib
- numpy
- matplotlib
- tensorflow==2.4.0
- streamlit
- pip
- cmake
- pip:
  - opencv-python-headless
  - pillow
  - cuda-python
  - cudnn-python-wrappers
       
