channels:
     - conda-forge
dependencies:
     - dlib
     - numpy
     - matplotlib
     - tensorflow==2.4.0
     - streamlit
     - cmake
     - pip:
       - opencv-python-headless
       - face-recognition
       - imageio-ffmpeg
       - imageio
       - pillow
       - ffmpeg-python
       - cuda-python
       - cudnn-python-wrappers
       - face_recognition
